kind: pipeline
name: default

steps:
- name: frontend
  image: node
  commands:
  - cd frontend
  - npm ci --registry=https://registry.npm.taobao.org
  - npm run build

- name: backend
  image: golang
  commands:
    - sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list
    - sed -i 's|security.debian.org/debian-security|mirrors.ustc.edu.cn/debian-security|g' /etc/apt/sources.list
    - apt-get update
    - apt-get install -y zip upx
    - sh build_go.sh

- name: gitea_release
  image: plugins/gitea-release
  settings:
    base_url: 
      from_secret: gitea_url
    api_key:
      from_secret: gitea_token
    files:
      - Robot_Monitor_Web_linux.zip
      - Robot_Monitor_Web_mac.zip
      - Robot_Monitor_Web_windows.zip
  when:
    event: tag
  